config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :post_likes
  root 'posts#index'

  get 'posts/filter/:filter' => 'posts#index', as: :filtered_posts

  resources :posts do
    resources :comments, only: [:create]
  end

  resource :session, only: %i[new create destroy]

  resources :users
  get 'signup', to: 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  before_save :set_slug

  has_many :comments, dependent: :destroy
  has_many :post_likes, dependent: :destroy
  has_many :user_likes, through: :post_likes, source: :user

  has_many :post_taggings, dependent: :destroy
  has_many :tags, through: :post_taggings

  validates :title, presence: true, uniqueness: { case_sensitive: false }

  scope :decending, -> { order(created_at: :desc) }

  scope :published, lambda {
    where('published_at < ? AND published_at IS NOT NULL', timestamp)
      .decending
  }
  scope :unpublished, lambda {
    where('published_at IS NULL OR published_at > ?', timestamp)
      .order('CASE WHEN published_at IS NULL THEN 0 ELSE 1 END, published_at DESC')
  }

  scope :with_tag, lambda { |tag_id|
    joins(:post_taggings).where(post_taggings: { tag_id: tag_id })
  }

  def to_param
    title.parameterize
  end

  def self.timestamp
    Time.now
  end

  def comment_count
    comments.count
  end

  private

  def set_slug
    self.slug = title.parameterize
  end
end

app/models/post_like.rb
class PostLike < ApplicationRecord
end

app/models/post_tagging.rb
class PostTagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :post_taggings, dependent: :destroy
  has_many :posts, through: :post_taggings
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :post_likes, dependent: :destroy
  has_many :liked_posts, through: :post_likes, source: :post

  has_secure_password

  validates :name, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def user_sign_out
    session[:user_id] = nil
  end

  def current_user
    user_id = session[:user_id]
    User.find_by(id: user_id) if user_id
  end

  helper_method :current_user

  def current_user?(user)
    current_user == user
  end

  helper_method :current_user?

  def require_sign_in
    return if current_user

    session[:intended_url] = request.url
    redirect_to new_session_path, alert: 'Please sign in first'
  end

  def require_admin
    return if current_user_admin?

    redirect_to root_url, alert: 'Unauthorized to perform this action'
  end

  def current_user_admin?
    current_user&.admin?
  end

  helper_method :current_user_admin?
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_sign_in
  before_action :set_post

  def create
    @user = current_user

    @comment = @post.comments.new(comment_params)
    @comment.user = @user

    @comment.save
    redirect_to post_path(@post, anchor: 'comment-form')
  end

  def destroy
    @comment = @post.comments.find(params[:id])

    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find_by!(slug: params[:post_id])
  end
end

app/controllers/post_likes_controller.rb
class PostLikesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_sign_in, except: %i[index show]
  before_action :require_admin, except: %i[index show]
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @unpublished_posts = Post.unpublished
    @tags = Tag.all

    tag = params[:filter] && Tag.find_by(name: params[:filter])

    @posts = tag ? Post.with_tag(tag.id).decending : Post.published
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :desc)
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice: 'Post updated successfully'
    else
      render :edit
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to post_path(@post), notice: 'Post created successfully'
    else
      render :new
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private # Everything below this line is private

  def post_params
    params.require(:post).permit(:title, :body, :published_at, tag_ids: [])
  end

  def find_post_by_id
    Post.find_by(id: params[:id])
  end

  def set_post
    @post = Post.find_by!(slug: params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])

    if user&.authenticate(params[:password])
      create_user_session(user)
    else
      flash.now[:alert] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    user_sign_out
    redirect_to posts_url, notice: 'Logged out successfully'
  end

  private

  def create_user_session(user)
    session[:user_id] = user.id

    redirect_to((session[:intended_url] || user), notice: 'Logged in successfully')
    session[:intended_url] = nil
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_sign_in, except: %i[new create]
  before_action :require_correct_user, only: %i[edit update destroy]

  def index
    @users = User.all
  end

  def show
    @user = find_user_by_id
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'Account created successfully'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Account updated successfully'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy

    user_sign_out

    redirect_to posts_url, notice: 'Account deleted successfully'
  end

  private

  def require_correct_user
    @user = find_user_by_id
    return if current_user?(@user)

    redirect_to root_url, alert: 'Unauthorized to perform this action'
  end

  def find_user_by_id
    User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_likes_helper.rb
module PostLikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def published(post)
    if post.published_at.present?
      post.published_at.strftime('%-b %-d, %Y')
    else
      'Not published yet'
    end
  end

  def tag_filter_dropdown(filter)
    @tags = Tag.all
    form_with url: '#', id: 'tag_filter_form', method: :get, class: 'bg-red' do |form|
      capture do
        concat form.select :filter, options_for_select([['All Posts', '']] + @tags.map do |t|
                                                                               [t.name, t.name]
                                                                             end, filter), {}, { id: 'filter', class: 'form-input-selector' }
      end
    end
  end

  def tag_filter_javascript
    javascript_tag <<~JS
      document.getElementById('filter').addEventListener('change', function(event) {
        var tag = event.target.value;
        if(tag) {
          window.location = '/posts/filter/' + tag;
        } else {
          window.location = '/posts';
        }
      });
    JS
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<div class="w-full px-10 py-6 mt-2 rounded-lg shadow-sm bg-slate-700/60">
  <%if current_user%>
    <div class="text-gray-700">
      <%= form_with(model: [post, comment], local: true, html: {id: 'comment-form'}) do |f| %>
        <%= render "shared/form_errors", errors:comment.errors %>
        <div class="mb-4">
          <%= f.label "Leave a comment", class: 'form-label mb-6'
    %>
          <%= f.text_area :content, rows: 3, class: 'form-input' %>
        </div>
        <div class="flex justify-start">
          <%= f.submit 'Add Comment', class: 'button-basic' %>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="flex justify-start items-center mt-4">
      <h3>Sign in/up to leave a comment</h2>
      <%= link_to "Sign In", new_session_path, class:"button-basic ml-10 mr-4"%>
      <%= link_to "Sign Up", signup_path, class:"button-basic"%>
    </div>
  <% end %>
</div>

app/views/comments/_list.html.erb
<div
    class="px-10 py-6 rounded-lg shadow-sm bg-slate-700/50 mt-5"
  >
  <h2 class="text-2xl font-bold hover:underline mb-2">Comments (<%= count %>)</h2>
  <div class="max-h-[50vh] overflow-auto">
    <% comments&.select(&:persisted?)&.each do |comment| %>
      <p class="mt-2"><%= comment.content %></p>
      <div class="flex items-center justify-between mb-6 mt-2">
        <div class="flex items-center">
          <span class="text-gray-400"><%= comment.user.name %></span>
        </div>
        <span class="text-sm text-gray-400"
          ><%= comment.created_at.strftime('%H:%M:%S %-b %-d, %Y') %></span
        >
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_form.html.erb
<div class="text-gray-700">
  <%= render "shared/form_errors", errors:post.errors %>
  <%= form_with(model: post, local: true, class: 'flex flex-col') do |f| %>
    <div class="mb-4">
      <%= f.label :title, class: 'form-label' %>
      <%= f.text_field :title, autofocus:true, class: 'form-input' %>
    </div>
    <div class="mb-4">
      <%= f.label :body, class: 'form-label' %>
      <%= f.text_area :body, rows: 7, class: 'form-input' %>
    </div>
    <div class="mb-4">
      <div class="form-check-boxes">
        <%= f.collection_check_boxes(:tag_ids, Tag.order(:name), :id, :name, {class:"form-checkbox"}) %>
      </div>
    </div>
    <div class="mb-10">
      <%= f.label :published_at, class: 'form-label' %>
      <div class="flex items-center w-full">
        <%= f.date_select :published_at, {}, { class: 'mt-1 mr-3 form-input-selector' } %>
      </div>
    </div>
    <div class="flex justify-start">
      <%= f.submit button_text, class: 'inline-flex items-center button-basic' %>
    </div>
  <% end %>
</div>

app/views/posts/_post_list_item.html.erb
<li>
  <div class="text-gray-100 mb-5">
    <div class="px-8 py-4 mx-auto rounded-lg shadow-sm bg-sky-950">
      <div class="mt-3">
        <%= link_to post.title, post_path(post), class:'text-2xl font-bold
        hover:underline' %>
        <div class="flex">
          <span class="text-sm text-gray-400"><%= published(post) %></span>
        </div>
        <p class="mt-2"><%= truncate(post.body, {length:300}) %></p>
      </div>
      <div class="flex items-center justify-between mt-4">
        <%= link_to 'Read More', post_path(post), class:'hover:underline
        text-violet-500' %>
        <div>
          <div class="flex items-center">
            <% post.tags&.each do |tag| %>
              <span
              class="px-2 py-1 mx-1 text-xs font-bold text-gray-100 bg-gray-600 rounded-full bg-gray-700"
              ><%= tag.name %></span
            >
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/posts/edit.html.erb
<h1 class="mb-8">Edit Post</h1>
<%= render 'form', post: @post, button_text:"Save" %>

app/views/posts/index.html.erb
<section class="admin">
  <% if current_user_admin? %>
    <div class="flex justify-end">
      <%= link_to new_post_path, class: "button-basic" do %>Create New Post <% end %>
    </div>
  <% end %>
</section>
<% if current_user_admin? %>
  <h2>Published Posts</h2>
<%else%>
  <h2>Posts</h2>
<% end %>
<div class="w-full">
  <div class="flex flex-col items-start justify-start text-gray-500 my-2">
    <%= tag_filter_dropdown(params[:filter]) %>
    <%= tag_filter_javascript %>
  </div>
  <ul>
    <% @posts.each do |post| %>
      <%= render "post_list_item", post: post %>
    <% end %>
  </ul>
  <% if current_user_admin? %>
    <h2>Unpublished Posts</h2>
    <ul>
      <% @unpublished_posts.each do |post| %>
        <%= render "post_list_item", post: post %>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1 class="mb-8">New Post</h1>
<%= render 'form', post: @post, button_text:"Create" %>

app/views/posts/show.html.erb
<%if current_user_admin?%>
  <section class="admin">
    <div class="flex justify-end">
      <%= link_to post_path(@post), method: :delete, data: { confirm: "Confirm you want to delete this post." }, class: "mb-4 mr-5 button-delete" do %> Delete <% end %>
      <%= link_to edit_post_path(@post), class: "mb-4 button-basic w-24" do %> Edit <% end %>
    </div>
  </section>
<% end %>
<section>
  <div class="text-gray-100 mb-5">
    <div class="px-10 py-6 rounded-lg shadow-sm bg-sky-950 min-h-[70vh]">
      <div class="mt-3">
        <h2>
          <%= @post.title %>
        </h2>
        <div class="flex">
          <span class="text-sm text-gray-400" >
            <%= published(@post) %>
          </span>
        </div>
        <div class="mt-2 mb-5">
          <% @post.tags&.each do |tag| %>
            <span class="px-2 mr-2 py-1 text-xs font-bold text-gray-100 bg-gray-600 rounded-full bg-gray-700">
              <%= tag.name %>
            </span>
          <% end %>
        </div>
        <p class="mt-2 whitespace-pre-wrap text-lg"><%= @post.body %></p>
      </div>
    </div>
  </div>
</section>
<section>
  <%= render 'comments/list', comments: @comments, count: @post.comment_count%>
  <%= render 'comments/form', post: @post, comment: @comment, button_text:"Save" %>
</section>

app/views/users/_form.html.erb
<div class="my-5 text-gray-700  max-w-2xl bg-sky-950 p-8 rounded-lg">
  <%= form_with(model: user,local:true) do |f| %>
    <%= render "shared/form_errors", errors: user.errors %>
    <div class="mb-4">
      <%= f.label :name, class: 'form-label' %>
      <%= f.text_field :name, autofocus:true, class: 'form-input' %>
    </div>
    <div class="mb-4">
      <%= f.label :email, class: 'form-label' %>
      <%= f.text_field :email, class: 'form-input' %>
    </div>
    <div class="mb-4">
      <%= f.label :password, class: 'form-label' %>
      <%= f.password_field :password, class: 'form-input' %>
    </div>
    <div class="mb-4">
      <%= f.label :password_confirmation, class: 'form-label' %>
      <%= f.password_field :password_confirmation, class: 'form-input' %>
    </div>
    <div class="flex justify-start">
      <%= f.submit button_text, class: 'inline-flex items-center button-basic' %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1 class="" >Edit</h1>
<%= render 'form', user: @user, button_text:'Update Account' %>

app/views/users/index.html.erb
<h1><%= pluralize(@users.count, "user") %></h1>
<ul class="mt-5">
  <% @users.each do |user| %>
    <li>
      <%= link_to user_path(user) do%>
        <h3>
          - <%= user.name %>: <%= user.email %>
        </h3>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1 class="" >Sign Up!</h1>
<%= render 'form', user: @user, button_text:'Create Account' %>

app/views/users/show.html.erb
<%# show user %>
<h1><%= @user.name %></h1>
<h3 class="mt-3 h-16"><%= mail_to(@user.email) %></h3>
<% if current_user?(@user)%>
  <div class="flex justify-start ">
    <%= link_to user_path(@user), method: :delete, data: { confirm: "Confirm you want to delete this account." }, class: "mb-4 mr-5 button-delete" do %> Delete <% end %>
    <%= link_to edit_user_path(@user), class: "mb-4 button-basic w-24" do %> Edit <% end %>
  </div>
<% end %>
<% if @user.comments.any? %>
  <div class="mt-5">
    <h2 class="mb-3">Comments</h2>
    <% @user.comments.each do |comment| %>
      <div class="flex flex-col mb-5 px-4 py-4 rounded-lg shadow-sm bg-slate-700/60">
        <h4>
          <%= link_to comment.post.title, post_path(comment.post) %>
        </h4>
        <p class="text-gray-500">
          <%= comment.created_at.strftime('%H:%M:%S %-b %-d, %Y') %>
        </p>
        <p class="text-gray-100 text-lg mt-4"><%= comment.content %></p>
      </div>
    <% end %>
  </div>
<% end %>