config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :post_likes
  root 'posts#index'

  get 'posts/filter/:filter' => 'posts#index', as: :filtered_posts

  resources :posts do
    resources :comments, only: [:create]
  end

  resource :session, only: %i[new create destroy]

  resources :users
  get 'signup', to: 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  before_save :set_slug

  has_many :comments, dependent: :destroy
  has_many :post_likes, dependent: :destroy
  has_many :user_likes, through: :post_likes, source: :user

  has_many :post_taggings, dependent: :destroy
  has_many :tags, through: :post_taggings

  validates :title, presence: true, uniqueness: { case_sensitive: false }

  scope :decending, -> { order(created_at: :desc) }

  scope :published, lambda {
    where('published_at < ? AND published_at IS NOT NULL', timestamp)
      .decending
  }
  scope :unpublished, lambda {
    where('published_at IS NULL OR published_at > ?', timestamp)
      .order('CASE WHEN published_at IS NULL THEN 0 ELSE 1 END, published_at DESC')
  }

  scope :with_tag, lambda { |tag_id|
    joins(:post_taggings).where(post_taggings: { tag_id: tag_id })
  }

  def to_param
    title.parameterize
  end

  def self.timestamp
    Time.now
  end

  def comment_count
    comments.count
  end

  private

  def set_slug
    self.slug = title.parameterize
  end
end

app/models/post_like.rb
class PostLike < ApplicationRecord
end

app/models/post_tagging.rb
class PostTagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :post_taggings, dependent: :destroy
  has_many :posts, through: :post_taggings
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :post_likes, dependent: :destroy
  has_many :liked_posts, through: :post_likes, source: :post

  has_secure_password

  validates :name, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: { case_sensitive: false }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_sign_in
  before_action :set_post

  def create
    @user = current_user

    @comment = @post.comments.new(comment_params)
    @comment.user = @user

    @comment.save
    redirect_to post_path(@post, anchor: 'comment-form')
  end

  def destroy
    @comment = @post.comments.find(params[:id])

    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find_by!(slug: params[:post_id])
  end
end

app/controllers/post_likes_controller.rb
class PostLikesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_sign_in, except: %i[index show]
  before_action :require_admin, except: %i[index show]
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @unpublished_posts = Post.unpublished
    @tags = Tag.all

    tag = params[:filter] && Tag.find_by(name: params[:filter])

    @posts = tag ? Post.with_tag(tag.id).decending : Post.published
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :desc)
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice: 'Post updated successfully'
    else
      render :edit
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to post_path(@post), notice: 'Post created successfully'
    else
      render :new
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private # Everything below this line is private

  def post_params
    params.require(:post).permit(:title, :body, :published_at, tag_ids: [])
  end

  def find_post_by_id
    Post.find_by(id: params[:id])
  end

  def set_post
    @post = Post.find_by!(slug: params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])

    if user&.authenticate(params[:password])
      create_user_session(user)
    else
      flash.now[:alert] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    user_sign_out
    redirect_to posts_url, notice: 'Logged out successfully'
  end

  private

  def create_user_session(user)
    session[:user_id] = user.id

    redirect_to((session[:intended_url] || user), notice: 'Logged in successfully')
    session[:intended_url] = nil
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_sign_in, except: %i[new create]
  before_action :require_correct_user, only: %i[edit update destroy]

  def index
    @users = User.all
  end

  def show
    @user = find_user_by_id
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'Account created successfully'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Account updated successfully'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy

    user_sign_out

    redirect_to posts_url, notice: 'Account deleted successfully'
  end

  private

  def require_correct_user
    @user = find_user_by_id
    return if current_user?(@user)

    redirect_to root_url, alert: 'Unauthorized to perform this action'
  end

  def find_user_by_id
    User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_likes_helper.rb
module PostLikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def published(post)
    if post.published_at.present?
      post.published_at.strftime('%-b %-d, %Y')
    else
      'Not published yet'
    end
  end

  def tag_filter_dropdown(filter)
    @tags = Tag.all
    form_with url: '#', id: 'tag_filter_form', method: :get, class: 'bg-red' do |form|
      capture do
        concat form.select :filter, options_for_select([['All Posts', '']] + @tags.map do |t|
                                                                               [t.name, t.name]
                                                                             end, filter), {}, { id: 'filter', class: 'form-input-selector' }
      end
    end
  end

  def tag_filter_javascript
    javascript_tag <<~JS
      document.getElementById('filter').addEventListener('change', function(event) {
        var tag = event.target.value;
        if(tag) {
          window.location = '/posts/filter/' + tag;
        } else {
          window.location = '/posts';
        }
      });
    JS
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div
  class="flash-notice px-4 py-3 rounded relative flex justify-center mb-4"
  role="alert"
>
    <span class="block sm:inline"><%= flash[:notice] %></span>
  </div>
<% end %>
<% if flash[:alert] %>
  <div
  class="flash-alert px-4 py-3 rounded relative flex justify-center mb-4"
  role="alert"
>
    <span class="block sm:inline"><%= flash[:alert] %></span>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mt-auto bg-sky-850 text-white py-4">
  <div class="mx-auto max-w-7xl">
    <div>&copy; 2023 Shane Schmaltz. All rights reserved.</div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="relative">
  <nav class="fixed bg-sky-850 max-w-7xl mx-auto w-[97vw]">
    <div class="w-full max-w-5xl container mx-auto">
      <div class="flex items-center flex-row">
        <%= link_to root_path do %>
          <div class="flex items-center">
            <div class="flex items-center">
              <div class="rounded-full overflow-hidden mr-3 w-20 h-20">
                <%= image_tag("logo") %>
              </div>
            </div>
          </div>
        <% end %>
        <div class="flex items-center space-x-4 justify-between w-full">
          <a
            href="/"
            class="bg-gray-900 text-white rounded-md px-3 py-2 text-lg font-medium"
            aria-current="page"
            >Posts</a
          >
          <div class="flex items-center">
            <% if current_user %>
              <h3>
                <%= link_to "Hello #{current_user.name}", current_user, class:"mr-4" %>
              </h3>
              <%= link_to "Sign Out", session_path, method: :delete, class:"button-basic"%>
            <% else%>
              <%= link_to "Sign In", new_session_path, class:"button-basic mr-4"%>
              <%= link_to "Sign Up", signup_path, class:"button-basic"%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>BlogOnEm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track":
    "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all',
    'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="/dist/output.css" rel="stylesheet" />
  </head>
  <body class="h-full">
    <%= render "layouts/header" %>
    <div class="h-full flex flex-col container mx-auto">
      <main class="flex-grow">
        <div class="mx-auto max-h-[85vh] overflow-auto container max-w-5xl mt-28">
          <%= render "layouts/flash" %>
          <%= yield %>
        </div>
      </main>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/shared/_form_errors.html.erb
<% if errors.any? %>
  <div
    class="error-notice bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4"
  >
    <strong class="font-bold">
      <%= "Error".pluralize(errors.count) %>
    </strong>
    <ul class="mt-1">
      <% errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>